# Generated by Django 3.2 on 2021-04-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrip_code', models.CharField(max_length=120)),
                ('symbol', models.CharField(max_length=120)),
                ('open_price', models.FloatField(default=0)),
                ('high_price', models.FloatField(default=0)),
                ('low_price', models.FloatField(default=0)),
                ('close_price', models.FloatField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'historic_data',
            },
        ),
    ]
